name: Build & Deploy

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
  
    - name: npm install
      run: npm install
    
    - name: gatsby build
      run: npm run-script build
      
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2
      env: 
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
